version: "3.3"

services:
  mern-client-react:
    build: ./client
    platform: linux/amd64
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app

  mern-server-express:
    build: ./server
    platform: linux/amd64
    ports:
      - "4000:5000"  # ✅ Fix: container runs on 5000, expose as 4000
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
